### ISSUE TITLE
Passar testes

### ISSUE THREAD

**Issue by jonatassalgado** [minhaportoalegre/verdade-ou-consequencia#6]

**Comment by leticia** [comment]
Oi, @jonatassalgado! Eu dei uma trabalhada no setup e nos testes da aplicação, e notei que a gente tem um arquivo de configuração do Travis, mas um webhook do Circle CI. Qual CI estamos usando pro projeto?

**Comment by jonatassalgado** [comment]
Oi @leticia,  a princípio CircleCI, mas se preferir podemos configurar outro. Podemos excluir o Tavis se ficarmos com CircleCI.

**Comment by leticia** [comment]
Belesma! Eu posso tirar a config do Travis, então. Ontem fiz passar os
testes unitários e de integração, falta só o Jasmine. :)
